// new/frontend/src/app/data-view/data-view.component.ts
import { Component } from '@angular/core';
import {Person} from "../models/person";
import {mockData} from "../data/mockData";

@Component({
  selector: 'app-data-view',
  imports: [],
  templateUrl: './data-view.component.html'
})
export class DataViewComponent {
  data: Person[] = mockData;
}

<table class="table table-bordered">
    <thead>
    <tr class="table-success">
        <th scope="col">n</th>
        <th scope="col">id</th>
        <th scope="col">name</th>
        <th scope="col">address</th>
        <th scope="col">birthDate</th>
        <th scope="col">email</th>
    </tr>
    </thead>
    <tbody>
        @for (person of data; track person.id) {
            <tr>
                <th scope="row">{{person.n}}</th>
                <td>{{person.id}}</td>
                <td>{{person.name}}</td>
                <td>{{person.address}}</td>
                <td>{{person.birthDate}}</td>
                <td>{{person.email}}</td>
            </tr>
        }
    </tbody>
</table>

// frontend/src/app/components/data-view.jsx
"use client";
import getTableData from "@/app/services/data-services";
import Filters from "@/app/components/filters";
import { useState } from "react";

export function DataView({ data }) {
  const [id, setId] = useState("");
  const [name, setName] = useState("");
  const [address, setAddress] = useState("");
  const [birthdate, setBirthdate] = useState("");
  const [email, setEmail] = useState("");
  const filterValues = {
    id: id,
    name: name,
    address: address,
    birthdate: birthdate,
    email: email,
  };
  const filterSetters = {
    setId: setId,
    setName: setName,
    setAddress: setAddress,
    setBirthdate: setBirthdate,
    setEmail: setEmail,
  };
  const { headers, rows } = getTableData(data, filterValues);

  return (
    <div>
      <Filters filterValues={filterValues} filterSetters={filterSetters} />
      <table className="table table-bordered border-secondary">
        <thead>
          <tr className="table-success">
            {headers.map((i) => (
              <th scope="col" key={i}>
                {i}
              </th>
            ))}
          </tr>
        </thead>
        <tbody>
          {rows.map((row) => {
            return (
              <tr key={row}>
                {row.map((cell) => (
                  <td key={cell}>{cell}</td>
                ))}
              </tr>
            );
          })}
        </tbody>
      </table>
    </div>
  );
}
